# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 06:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20151210_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-update_time'], 'verbose_name': '列表', 'verbose_name_plural': '列表'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorder_auditor', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
